#!/usr/bin/env python3
"""
quantum.py — a language set generated by rhyme, not by dice.

The forge already has a generator: `corpus.Fuzzer`, seeded, reproducible
in the sense that replaying the same seed replays the same draws. That
is reproducible but not *addressable*. Case `fz-well-137` cannot be
regenerated without first regenerating the hundred and thirty-six that
came before it, and its text is a fact about CPython's Mersenne
Twister as much as about EZR.

This module generates the same kind of material with no random source
at all.

## The realm

Every construction site in a program is held as a **superposition**: an
ordered tuple of the productions the settled core admits there. Nothing
is drawn. The site is **collapsed** by an address — the path from the
root, as text — hashed with FNV-1a and taken modulo the number of
candidates. So the choice at `2/cond/left` is a pure function of the
phrase and that path, and of nothing else: not of call order, not of
what was generated before it, not of the interpreter's hash seed.

Two consequences, and they are the reason this exists:

* Any subtree can be regenerated on its own. You can ask for stanza 9's
  else-branch without producing stanzas 0 through 8.
* The text is a fact about the phrase. `Realm("entangle the parser")`
  emits the same corpus on any machine, any Python, any year.

## The rhyming rule

Determinism that ranges freely is just a slower fuzzer. What makes this
a *set* rather than a heap is that the programs are emitted in couplets
under a constraint borrowed from verse.

The **foot** of a program is the tuple of its last `k` token kinds,
EOF excluded — the sound it ends on. Two programs **rhyme** when their
feet are equal. A **couplet** is a rhyming pair whose skeletons
(`contract.skeleton`, constants erased) differ: same sound, different
sense. A pair that rhymed by being the same program twice would teach
the corpus nothing, so it is rejected by construction.

The first line of a couplet collapses freely. The second is searched:
nonces are tried in order and the first whose foot matches — and whose
skeleton does not — is the answer. The search is bounded, and when the
bound is reached the couplet **withholds**, which is the same thing the
forge does below its fourth tier and for the same reason. An unrhymed
line invented to fill the slot would be a claim nobody checked.

## What the constraint is worth

A foot is a claim about tokenization, and it is the one part of a
program that four independently derived scanners must compute
identically for anything downstream to mean what it says. The forge's
own README records the four splitting over a bare `<` before a single
test existed. `law_rhyme` below asks the question directly: all four
scanners, both members of the couplet, one foot. A scanner that reads a
different ending reads a different program, and that is a finding about
the language rather than a bug report against one file.

Nothing here adds syntax. Every node comes from `contract`, every
program is printed by `contract.unparse`, so a generated line is in the
settled core by construction and the twenty pairings decide whether it
is in the *language*.

Codric Enterprise · 2026
"""

from __future__ import annotations

import argparse
import os
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Sequence, Tuple

from contract import (Bin, Bool, Call, If, Let, Lst, Num, Prog, Str, Var,
                      skeleton, unparse)
from lexers import LEXERS

HERE = os.path.dirname(os.path.abspath(__file__))
OUT_DIR = os.path.join(HERE, "generated")

#: The scanner the generator itself consults when it needs a foot.
#: It holds no privilege — `law_rhyme` re-asks all four, and a foot
#: only this one can see is exactly the finding worth having.
REFERENCE_LEXER = "L1-regex-master"


# ═════════════════════════════════════════════
# Collapse — the only source of choice
# ═════════════════════════════════════════════

_FNV_OFFSET = 0xCBF29CE484222325
_FNV_PRIME = 0x100000001B3
_MASK64 = 0xFFFFFFFFFFFFFFFF


def fnv1a(data: bytes) -> int:
    """FNV-1a, 64-bit, written out rather than imported.

    Python's built-in `hash()` is salted per process, so a generator
    built on it would emit a different corpus on every run and call it
    deterministic. `hashlib` would do, but this is four lines and can
    be checked by eye against the published constants, which matters
    more here than speed: the whole claim of this module is that the
    text is a function of the phrase.
    """
    h = _FNV_OFFSET
    for byte in data:
        h ^= byte
        h = (h * _FNV_PRIME) & _MASK64
    return h


# ═════════════════════════════════════════════
# The vocabulary the core already admits
# ═════════════════════════════════════════════

NAMES = ("a", "b", "c", "n", "x", "y")
FUNCS = ("f", "g", "h", "len", "head", "tail", "show")
ARITH = ("+", "-", "*", "/")
COMPARE = ("<", ">", "<=", ">=", "==", "!=")
WORDS = ("realm", "phase", "thread", "vowel", "ledger")

#: Sites, in a fixed order. The order is part of the address space:
#: changing it changes every program, which is why it is written once
#: here and never sorted, shuffled or extended conditionally.
ATOM_SITES = ("num", "var", "bool", "str")
FORM_SITES = ("bin", "cmp", "if", "let", "list", "call")


@dataclass
class Realm:
    """One phrase, one deterministic language set.

    `k` is the length of the rhyme foot. `depth` bounds nesting, which
    bounds nothing about correctness — it bounds how long a line takes
    to read, and an unreadable witness is a witness nobody checks.
    """

    phrase: str
    k: int = 4
    depth: int = 3
    budget: int = 512

    # ── collapse ──
    def collapse(self, addr: str, n: int) -> int:
        """Pick one of `n` candidates at `addr`. No state, no draws."""
        if n <= 0:
            raise ValueError("cannot collapse an empty superposition")
        return fnv1a(f"{self.phrase}\x00{addr}".encode("utf-8")) % n

    def choice(self, addr: str, options: Sequence):
        return options[self.collapse(addr, len(options))]

    # ── construction ──
    def atom(self, addr: str, bound: Sequence[str]):
        site = self.choice(addr + "/a", ATOM_SITES)
        if site == "num":
            return Num(float(self.collapse(addr + "/n", 100)))
        if site == "var":
            pool = tuple(bound) if bound else NAMES
            return Var(self.choice(addr + "/v", pool))
        if site == "bool":
            return Bool(self.collapse(addr + "/b", 2) == 1)
        return Str(self.choice(addr + "/s", WORDS))

    def expr(self, addr: str, depth: int, bound: Tuple[str, ...]):
        """One expression. Every recursive call extends the address,
        so a subtree's shape depends on where it sits and not on how
        many nodes happened to be built before it."""
        if depth <= 0:
            return self.atom(addr, bound)

        site = self.choice(addr + "/f", FORM_SITES)

        if site == "bin":
            return Bin(self.choice(addr + "/op", ARITH),
                       self.expr(addr + "/l", depth - 1, bound),
                       self.expr(addr + "/r", depth - 1, bound))
        if site == "cmp":
            return Bin(self.choice(addr + "/op", COMPARE),
                       self.expr(addr + "/l", depth - 1, bound),
                       self.expr(addr + "/r", depth - 1, bound))
        if site == "if":
            return If(self.expr(addr + "/c", depth - 1, bound),
                      self.expr(addr + "/t", depth - 1, bound),
                      self.expr(addr + "/e", depth - 1, bound))
        if site == "let":
            name = self.choice(addr + "/nm", NAMES)
            value = self.expr(addr + "/v", depth - 1, bound)
            return Let(name, value,
                       self.expr(addr + "/bd", depth - 1,
                                 bound + (name,)))
        if site == "list":
            count = 1 + self.collapse(addr + "/len", 3)
            return Lst([self.expr(f"{addr}/i{i}", depth - 1, bound)
                        for i in range(count)])
        count = self.collapse(addr + "/argc", 3)
        return Call(self.choice(addr + "/fn", FUNCS),
                    [self.expr(f"{addr}/a{i}", depth - 1, bound)
                     for i in range(count)])

    def program(self, addr: str) -> str:
        """A whole program, as source. `Prog` with no defs: a def would
        put a `def` keyword at the head of every line and flatten the
        variety the foot is supposed to discriminate."""
        return unparse(Prog([], self.expr(addr, self.depth, ())))


# ═════════════════════════════════════════════
# Feet and rhyme
# ═════════════════════════════════════════════

def foot(src: str, k: int, lexer: str = REFERENCE_LEXER,
         lexers: Optional[Dict] = None) -> Optional[Tuple[str, ...]]:
    """The last `k` token kinds, EOF excluded.

    None when the text does not scan, or scans to fewer than `k`
    tokens. Both mean the same thing for rhyming purposes: this line
    has no ending to match, so it cannot be half of a couplet.

    `lexers` names the registry to resolve `lexer` against, defaulting
    to the four built in. It is the same seam `forge.build_pairs` has,
    and for the same reason: a law that can only be asked about the
    scanners that already ship cannot be shown to catch a scanner that
    reads an ending wrongly, and a law nobody can fail is decoration.
    """
    lx = LEXERS if lexers is None else lexers
    out = lx[lexer](src)
    if not out.ok:
        return None
    kinds = [t.kind for t in out.toks if t.kind != "EOF"]
    if len(kinds) < k:
        return None
    return tuple(kinds[-k:])


def rhymes(a: str, b: str, k: int, lexer: str = REFERENCE_LEXER,
           lexers: Optional[Dict] = None) -> bool:
    fa = foot(a, k, lexer, lexers)
    fb = foot(b, k, lexer, lexers)
    return fa is not None and fa == fb


@dataclass
class Couplet:
    """Two lines that end alike and say different things.

    `withheld` carries the reason when the second line could not be
    found inside the budget. A withheld couplet is reported and
    counted; it is never quietly dropped, and never filled with an
    unrhymed line to keep the tally round.
    """

    index: int
    first: str
    second: Optional[str] = None
    foot: Optional[Tuple[str, ...]] = None
    tries: int = 0
    withheld: str = ""

    @property
    def ok(self) -> bool:
        return self.second is not None

    def lines(self) -> List[str]:
        return [self.first] + ([self.second] if self.second else [])


def couplet(realm: Realm, index: int) -> Couplet:
    """Collapse the first line, then search for one that answers it.

    The search is an ordered walk over nonces, not a sample, so the
    second line is as addressable as the first: it is the least nonce
    that rhymes, which is a definition and not a draw.
    """
    first = realm.program(f"{index}:0")
    target = foot(first, realm.k)
    if target is None:
        return Couplet(index, first,
                       withheld="first line has no foot to answer")

    seen = skeleton_of(first)
    for nonce in range(1, realm.budget + 1):
        cand = realm.program(f"{index}:{nonce}")
        if foot(cand, realm.k) != target:
            continue
        if skeleton_of(cand) == seen:
            continue                      # same sense: not a rhyme
        return Couplet(index, first, cand, target, nonce)

    return Couplet(index, first, None, target, realm.budget,
                   f"no answering line within {realm.budget}")


def skeleton_of(src: str, lexer: str = REFERENCE_LEXER) -> str:
    """Skeleton of the text, via the reference pair. Used only to
    reject a rhyme against itself, so a parse failure is reported as
    its own distinct sense rather than raising."""
    from parsers import parse_earley
    out = LEXERS[lexer](src)
    if not out.ok:
        return f"<lex:{out.fail.defect}>"
    po = parse_earley(out.toks)
    if not po.ok:
        return f"<parse:{po.fail.defect}>"
    return skeleton(po.ast)


def stanzas(realm: Realm, count: int) -> List[Couplet]:
    return [couplet(realm, i) for i in range(count)]


# ═════════════════════════════════════════════
# The law the rhyme makes checkable
# ═════════════════════════════════════════════

def law_rhyme(cp: Couplet, k: int,
              lexers: Optional[Dict] = None) -> List[str]:
    """Every scanner reads the same ending.

    A foot is the one claim about a program that all four scanners must
    compute identically before anything downstream can mean what it
    says. This asks twice: that the scanners agree with each other on
    each line, and that the couplet still rhymes under each of them.
    The second is not implied by the first — four scanners could agree
    on two feet that differ from one another, and the pair would be a
    couplet only in the reference scanner's reading.
    """
    lx = LEXERS if lexers is None else lexers
    out: List[str] = []
    if not cp.ok:
        return out

    for line in cp.lines():
        feet = {name: foot(line, k, name, lx) for name in lx}
        distinct = set(feet.values())
        if len(distinct) > 1:
            out.append(f"couplet {cp.index}: scanners split on the foot "
                       f"of {line!r}: "
                       + "; ".join(f"{n}={f}" for n, f in feet.items()))

    for name in lx:
        fa = foot(cp.first, k, name, lx)
        fb = foot(cp.second, k, name, lx)
        if fa is None or fa != fb:
            out.append(f"couplet {cp.index}: does not rhyme under "
                       f"{name}: {fa} vs {fb}")
    return out


# ═════════════════════════════════════════════
# Running the set through the matrix
# ═════════════════════════════════════════════

@dataclass
class RealmReport:
    phrase: str
    k: int
    pairs: int = 0
    lines: int = 0
    couplets: int = 0
    withheld: List[Couplet] = field(default_factory=list)
    rhyme_violations: List[str] = field(default_factory=list)
    divergences: List[str] = field(default_factory=list)

    @property
    def clean(self) -> bool:
        return not self.rhyme_violations and not self.divergences

    def summary(self) -> str:
        state = "converged" if self.clean else "SPLIT"
        return (f"{self.phrase!r}: {self.couplets} couplets, "
                f"{self.lines} lines, {self.pairs} pairings — {state}")


def observe(realm: Realm, count: int) -> RealmReport:
    """Generate the set, then let every pairing read it.

    The forge owns the matrix, so this borrows it rather than building
    a second one: same pairs, same run_one, same verdicts. What is new
    is the material and the rhyme law over it.
    """
    from forge import Forge, build_pairs

    pairs = build_pairs()
    # budget=0: this borrows the matrix, not the fuzz loop. The
    # material under test is the rhyming set, and a forge that also
    # went fuzzing would be reporting on a different corpus.
    forge = Forge(budget=0, verbose=False)
    rep = RealmReport(realm.phrase, realm.k, pairs=len(pairs))

    for cp in stanzas(realm, count):
        if not cp.ok:
            rep.withheld.append(cp)
            continue
        rep.couplets += 1
        rep.rhyme_violations.extend(law_rhyme(cp, realm.k))

        for line in cp.lines():
            rep.lines += 1
            verdicts: Dict[str, List[str]] = {}
            for p in pairs:
                r = forge.run_one(p, line)
                key = f"CRASH[{r.crash}]" if r.crash else r.verdict
                verdicts.setdefault(key, []).append(p.name)
            if len(verdicts) > 1:
                winner = max(verdicts.values(), key=len)
                agreed = next(v for v, m in verdicts.items()
                              if m is winner)
                for v, members in verdicts.items():
                    if members is winner:
                        continue
                    rep.divergences.append(
                        f"{line!r}: {', '.join(members)} said {v[:60]!r}, "
                        f"{len(winner)} others said {agreed[:60]!r}")
    return rep


def emit(realm: Realm, couplets: Sequence[Couplet],
         path: Optional[str] = None) -> str:
    """Write the set to disk as readable EZR, couplet by couplet."""
    slug = "".join(ch if ch.isalnum() else "-"
                   for ch in realm.phrase.lower())[:40].strip("-")
    path = path or os.path.join(OUT_DIR, f"realm-{slug}.ezr")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as fh:
        fh.write(f"# realm: {realm.phrase!r}\n")
        fh.write(f"# foot: last {realm.k} token kinds\n")
        fh.write("# GENERATED by quantum.py — regenerate, do not edit.\n\n")
        for cp in couplets:
            if not cp.ok:
                fh.write(f"# couplet {cp.index} withheld: {cp.withheld}\n\n")
                continue
            fh.write(f"# couplet {cp.index}  foot={'.'.join(cp.foot)}"
                     f"  found at nonce {cp.tries}\n")
            fh.write(cp.first + "\n")
            fh.write(cp.second + "\n\n")
    return path


# ═════════════════════════════════════════════
# CLI
# ═════════════════════════════════════════════

def main(argv: Optional[Sequence[str]] = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[1])
    ap.add_argument("--phrase", default="entangle the parser",
                    help="the phrase the whole set collapses from")
    ap.add_argument("--stanzas", type=int, default=8)
    ap.add_argument("-k", "--foot", type=int, default=4,
                    help="rhyme foot length, in token kinds")
    ap.add_argument("--depth", type=int, default=3)
    ap.add_argument("--emit", action="store_true",
                    help="also write the set to generated/")
    ap.add_argument("--quiet", action="store_true")
    args = ap.parse_args(argv)

    realm = Realm(args.phrase, k=args.foot, depth=args.depth)
    cps = stanzas(realm, args.stanzas)

    if not args.quiet:
        print(f"realm {args.phrase!r}  foot={args.foot}  "
              f"depth={args.depth}\n")
        for cp in cps:
            if not cp.ok:
                print(f"  couplet {cp.index}: withheld — {cp.withheld}")
                continue
            print(f"  couplet {cp.index}  foot={'.'.join(cp.foot)}"
                  f"  (nonce {cp.tries})")
            print(f"    {cp.first}")
            print(f"    {cp.second}")
        print()

    rep = observe(realm, args.stanzas)
    print(rep.summary())
    for w in rep.withheld:
        print(f"  withheld {w.index}: {w.withheld}")
    for v in rep.rhyme_violations:
        print(f"  rhyme: {v}")
    for d in rep.divergences:
        print(f"  split: {d}")

    if args.emit:
        print(f"  wrote {emit(realm, cps)}")

    return 0 if rep.clean else 1


if __name__ == "__main__":
    raise SystemExit(main())


__all__ = ["Realm", "Couplet", "RealmReport", "fnv1a", "foot", "rhymes",
           "couplet", "stanzas", "law_rhyme", "observe", "emit",
           "skeleton_of", "REFERENCE_LEXER"]
